name: Java CI with Gradle

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure gradle
        run: ./gradlew

      - name: Check License
        run: ./gradlew checkLicense --full-stacktrace

      - name: Build with Gradle
        run: ./gradlew build --full-stacktrace

      - name: Run tests
        run: ./gradlew test --full-stacktrace

      - name: Publish to box
        run: ./gradlew publish --full-stacktrace
        env:
          VERSION: ${{ steps.get_tag_name.outputs.VERSION }}
          PUBLISH_TOKEN: ${{ secrets.BOX_PUBLISH_TOKEN }}